
TYPE
	PgsEvtStatus : 
		(
		PGS_EVT_ST_OK,
		PGS_EVT_ST_RUNNING,
		PGS_EVT_ST_DISABLED,
		PGS_EVT_ST_INVALID_IDENT,
		PGS_EVT_ST_MEM_FAIL,
		PGS_EVT_ST_START_FAIL,
		PGS_EVT_ST_STOP_FAIL,
		PGS_EVT_ST_INVALID_GROUP
		);
END_TYPE
