
TYPE
	PgsFsStatus : 
		(
		PGS_FILE_ST_OK,
		PGS_FILE_ST_RUNNING,
		PGS_FILE_ST_DISABLED,
		PGS_FILE_ST_INVALID_IDENT,
		PGS_FILE_ST_OPEN_FAIL,
		PGS_FILE_ST_FILE_ERROR,
		PGS_FILE_ST_DEVICE_ERROR
		);
END_TYPE
