
TYPE
	PgsSshStatus : 
		(
		PGS_TNET_ST_OK,
		PGS_TNET_ST_RUNNING,
		PGS_TNET_ST_DISABLED,
		PGS_TNET_ST_INVALID_IDENT,
		PGS_TNET_ST_OPENING,
		PGS_TNET_ST_CLOSING,
		PGS_TNET_ST_CLOSED (*Device not open*)
		);
END_TYPE
